### ISSUE TITLE
PwmClock - BPM (V/Oct) input doesn't accept clock signal from "Midi > CV module"

### ISSUE THREAD

**Issue by anyway** [docb/dbRackSequencer#22]
The "BPM (V/Oct) Input" of "PwmClock" does not accept the clock signal from the VCV Rack module "Midi > CV". The clock rate jumps around like crazy. My DAW (Bitwig) is set to 110 BPM in this case. I also tried different CLK/N divider settings with the CLK/N output... to no success.

Is there anything special that needs to be considered for synchronization? With Impromtu's "CLOCKED" it works fine.

<img width="401" alt="grafik" src="https://user-images.githubusercontent.com/1565766/230761213-7af96ad4-3f8f-4e3d-920c-1886f5323897.png">

My System:
dbRackSequencer 2.2.2
VCV Rack Pro 2.3.0
MacOS 12.6
MacBook Pro M1 Max

**Comment by docb** [comment]
hi, thanks for reporting.
the BPM input of PwmClock does only support BPM CV and no clock signal. The origin reason is that PwmClock is designed as one of many building blocks for using VCVRack without a DAW. However i did not try this in production but at least you can use start stop of midi-cv to start and stop PwmClock. This should be accurate for a while if BPM is set to the DAW tempo.
To automate setting the BPM you can use the mini Clocked as shown in the image:
![image](https://user-images.githubusercontent.com/1134412/230763234-2b51a69f-2773-458d-be48-98bf511b0969.png)
Note that because of the higher bpm resolution the BPM will wobble between 134.99 and 135.01 in this example.

I will think about supporting clock sync in future versions.
Best regards

**Comment by anyway** [comment]
Thanks for your fast reply, explanation of the problem and the patch as a workaround. Now I understand.

To get your workaround to work, Impromptu's CLKD needs to have "BPM out is CV when ext sync" set in the settings so that BPM no longer jumps in PwmClock.

Now, however, a new problem has arisen and that is that start and stop of Bitwig are somehow not transferred to the "Midi > CV" module as expected. In between even the audio-egine crashes. In Ableton this is similar (without crashes). I have seen in the VCV forum that other people also have problems with the transportation signals. So I'll tinker a bit more and see if I can somehow get this solved to fit my purposes. Now that I know what it's all about, I'll figure it out somehow.

I love your last patch on PatchStorage (https://patchstorage.com/vcv-rack-showcase-docb-plugins-xxi-aseq/) and am experimenting on a small Berlin School project with ASEQ... Great sequencer! :-) 
Thanks for sharing your great modules and thanks for your kind support.
