### ISSUE TITLE
Suggestion: ACC, chords and smooth pattern switch

### ISSUE THREAD

**Issue by scheichreisuli** [docb/dbRackSequencer#24]
Hello,

using ACC to switch patterns of 'chords' was and is still a challenge for me. Please add a short description to the ADD-doc that mentions how to set the number of patterns ACC should recall from chords before it sends a trigger (i.e. for loops). It took me hours to find out, that setting the Trsh-value to 0.6 and the Step-value to 0.1 will address chord's patterns 0-6.

It would be nice to enhance ACC with a feature to set the number of patterns with up- and down-arrows like the edit-section of chords than fiddling around with the Trsh-knob.

I would like to have a random-option (or modes like arpeggiators offer) to switch between the chord-patterns set by ACC. Currently there is only a loop-option by resetting ACC using self-patching.

I currently have not found out how to smoothly blend the change of chord-patterns. Please make a short showcase that shows how to 'glide' from one chord-pattern smoothly into another to make nice pad-carpets.

Your modules are wonderful and so CPU-efficient. Thank you for your work.

Keep healthy.
Peace

**Comment by docb** [comment]
hi,
i think that ACC may be not the most convenient module to use in this case.
I would suggest to use PMod and OFS:

![image](https://github.com/docb/dbRackSequencer/assets/1134412/6e27cc26-d8b1-4196-996c-f75bbbcfa577)

In PMod set size to 10 and Mod to the count of steps i.e. 6 in your case. In OFS set scale to 0.1
PMod will then cycle through the chords on clock signals. (this is limited to max 32 steps)

When you want to have random chords you can use RndH2 with Range = 0.05.

Originally ACC should have been a simple accumulator which has a clk to advance and rst to reset.
The thresh and eoc trigger came later due to feature requests. These are only for convenience in my view
as you still can reset the ACC e.g. every 6th clock signal via a clock divider. 

![image](https://github.com/docb/dbRackSequencer/assets/1134412/c137086f-9c91-44cc-a456-d013a2b0f685)

So i would not touch this and make further special features for the ACC. 
May be a new module which is specially designed for controlling chords, but as long all usecases can be simply fulfilled by using other modules i don't think it makes sense.

Blending chords
There are two different cases: 
- blending or gliding pitch can be done with a slew limiter.
- morphing chords is much more complicated as you will need either 
   - two alternate sound sources which are crossfaded (more complex patch) 
   - one sound source per chord and scan through (e.g. using Scanner from hetrickcv) (more CPU usage)
   - some other methods i didn't considered/discovered by now (e.g. using polyphony - fading in out channels)

May be i will make a showcase on my youtube channel.

best regards
