### ISSUE TITLE
ACC TRIG behaviour [enhancement]

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackSequencer#8]
Dear Christian,

Currently TRIG input of the ACC is sending a pulse if the output voltage is crossing 0V. 

I'd like to propose a **new knob** (or context-menu settings) that would allow changing **the breakpoint voltage** from 0 to something else. By self-patching the reset socket it could re-start the loop nicely.

<img width="547" alt="image" src="https://user-images.githubusercontent.com/34127628/175362940-ef28095b-3874-4e2d-960c-3fc3060cf107.png">

Cheers, Andras

**Comment by forever-withyou** [comment]
Hello,
thank you Christian for all the hard work on your modules, lot's of great stuff as I said few days ago, they are steadily taking over my rack more and more ^^ and nice clean minimalist design style too heh. Most of your modules are really well thought out, however ACC in my opinion has major hole in logic design wise - or maybe I'm stupid one and I'm just missing something. 

Anyway, as for the topic I would like to point out one more issue. If you self patch ACC, even if it worked as you propose (as I thought it already should) then you will be losing RST input and will need to do stupid extra module stuff like extra sum module to connect RST from clock perhaps or maybe even CV-Map configured for RST? - stupid.

So my suggestion is to make it "self patched" by default - basically add one more knob thats called "reset on X step" just go away with this self patch thing entirely, dedicated knob to autoreset, because self patching is unnecessary it should be basic function of module - because losing RST input is stupid - its absolutely needed I think - no need to complicate things needlessly.

**Comment by docb** [comment]
indeed, i use it in this case like so:
![acc](https://user-images.githubusercontent.com/1134412/182033113-69a41301-2d75-4a51-ac84-e94337780a88.png)

 does not bother me.

changing to virtual self patched by default is not possible because i would destroy someones patches.
a knob + port i won't do because there is no space left.
the only thing i could do is to set this mode in the menu (default false). but i am not sure if this is good, have to think about.

**Comment by firolightfog** [comment]
Changes in v2.1.0 pre-release seem to be fine.
